config/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('contourshow/', include('contourshow.urls')),
    path('matrix/', include('matrix.urls')),
    path('common/', include('common.urls')),
    path('', index, name='index'),
]

matrix/urls.py
from django.urls import path
from .view.base_views import *

app_name = 'matrix'

urlpatterns = [
    path('', index, name='index'),
    path('program_guide/<str:name>/', program_guide, name='program_guide'),
    path('tuner_management/<str:name>/', tuner_management, name='tuner_management'),
    path('register/<str:name>/', register, name='register'),
    path('calibration/<str:name>/', calibration, name='calibration'),
    path('csv_harmonic/<str:name>/', csv_harmonic, name='csv_harmonic'),
    path('gain_sweep/<str:name>/', gain_sweep, name='gain_sweep'),
    path('pa_ruggedness/<str:name>/', pa_ruggedness, name='pa_ruggedness'),
    path('common_trx_plan/<str:name>/', common_trx_plan, name='common_trx_plan'),
    path('data_analysis/<str:name>/', data_analysis, name='data_analysis'),
    path('simple_function/<str:name>/', simple_function, name='simple_function'),
    path('general_measurements/<str:name>/', general_measurements, name='general_measurements'),
    path('traditional_csv/<str:name>/', traditional_csv, name='traditional_csv'),
    path('special_test/<str:name>/', special_test, name='special_test'),
    path('download/<str:file_name>/', download_file, name='download_file'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>', question_views.question_vote, name='question_vote'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

matrix/models.py
from django.db import models

# Create your models here.

templates/matrix/1_program_guide/control_desk.html
{% extends "matrix/matrix_base.html" %}
{% block title %}
<title>Control Desk</title>
{% endblock %}
{% block main_contents %}
<div class="container ms-5">
    <h1 class="mb-4">Control Desk</h1>
    <img src="/static/matrix/images/control_1.png" class="img-fluid rounded" alt="control_1">
    <h3 class="mt-5">Test Control</h3>
    <ul class="ps-4">
        <li>Auto-Scroll (F11) : 테스트 결과 자동 스크롤</li>
        <li>Pause Test (F12) : 테스트 일지 정지 (Running 중에만 활성화)</li>
        <li>Pause for 10 seconds (Ctrl + F12) : 10초간 테스트 일시정지 (Running 중에만 활성화)</li>
    </ul>
    <h3 class="mt-5">UDR</h3>
    <ul class="ps-4">
        <li>Make UDR Sheet : UDR Directory로부터 Rx Common Plan에 사용하는 UDR Sheet를 생성한다.</li>
        <li>Change Format : R&D UDR(*.csv)과 NPI UDR(*.txt)간의 상호변환</li>
    </ul>
    <h3 class="mt-5">Oscilloscope</h3>
    <ul class="ps-4">
        <li> Capture Screen : OSC의 화면을 Capture 후 저장한다.</li>
    </ul>
    <h3 class="mt-5">Loss File</h3>
    <ul class="ps-4">
        <li>Make Loss File From S2P : S2P File들을 선택하여 Loss File로 변환한다.</li>
    </ul>
    <h3 class="mt-5">Manual Command & Response</h3>
    <ul class="ps-4">
        <li>직접 명령어로 장비를 제어할 수 있다.</li>
    </ul>
    <h3 class="mt-5">Spectrum Analyzer</h3>
    <ul class="ps-4">
        <li>Capture Screen : SA의 화면을 Capture 후 저장한다.</li>
        <li>Get Trace Data : SA의 Trace를 CSV 파일로 저장한다.</li>
    </ul>
    <h3 class="mt-5">Mini-Circuits SP6Tx2</h3>
    <ul class="ps-4">
        <li>SP6T 두 개가 붙은 파란색 Switch Box를 컨트롤한다.</li>
    </ul>
    <h3 class="mt-5">Network Analyzer</h3>
    <ul class="ps-4">
        <li>Download SNP File : NA로부터 SNP 파일을 얻어온다.</li>
        <li>Cont ON : SNP 파일을 다운로드 받은 후 NA를 Continuous로 할 것인지 결정한다.</li>
        <li>Download State : NA의 상태를 파일로 저장한다.</li>
        <li>Upload State : NA의 상태 파일을 업로드한다.</li>
    </ul>
    <h3 class="mt-5">Noise Figure Analyzer</h3>
    <ul class="ps-4">
        <li>Download State : NFA의 상태를 파일로 저장한다.</li>
        <li>Upload State : NFA의 상태 파일을 업로드한다.</li>
    </ul>
    <h3 class="mt-5">Signal Generator</h3>
    <ul class="ps-4">
        <li>Get All Waveforms : SG에 있는 모든 Waveform을 리스팅한다.</li>
        <li>Set Copied Waveform : 현재 클립보드에 복사된 Waveform을 SG에 설정한다.</li>
    </ul>
    <h3 class="mt-5">Maury Tuner</h3>
    <ul class="ps-4">
        <li>Initialize Tuner : Tuner를 초기화한다.</li>
        <li>Set Freq : Tuner 주파수 설정</li>
        <li>Set VSWR/Phase : Tuner의 VSWR/Phase를 이동한다.</li>
        <li>Combine Tuner Cal File (*.tun) : Tune Calibration File들을 합친다.</li>
    </ul>
    <h3 class="mt-5">Power Supply</h3>
    <ul class="ps-4">
        <li>Calibrate Current : Power Supply의 Leakage Current을 측정하여 Current를 읽을 때 이 값만큼 제외하고 읽게 한다.</li>
        <li>Calibration 후 정확도가 상당히 상승하는 것을 확인할 수 있다.</li>
    </ul>
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>Calibration 시 Power Supply에는 아무것도 연결하지 않아야 한다 </div>
    </div>
</div>


{% endblock %}

templates/matrix/1_program_guide/instrument.html
{% extends "matrix/matrix_base.html" %}
{% block title %}
<title>Instrument & Flow Configurations</title>
{% endblock %}
{% block main_contents %}
<div class="container ms-5">
    <h1 class="mb-4">Instrument & Flow Configurations</h1>
</div>


{% endblock %}

templates/matrix/1_program_guide/loop_control.html
{% extends "matrix/matrix_base.html" %}
{% block title %}
<title>Control Desk</title>
{% endblock %}
{% block main_contents %}
<div class="container ms-5">
    <h1 class="mb-4">Group/Loop Control</h1>
</div>


{% endblock %}

templates/matrix/1_program_guide/start_matrix.html
{% extends "matrix/matrix_base.html" %}
{% block title %}
<title>Start Matrix</title>
{% endblock %}
{% block main_contents %}
<div class="container ms-5">
    <h1 class="mb-4">Start Matrix</h1>
    <h3 class="mt-5" id="설치-방법">설치 방법</h3>
    <ol>
        <li class="mb-4 pb-3" >
            <strong>모델 압축파일을 받아서 적당한 곳에 압축을 푼다.</strong>
            <ul class="ps-4">
                <li>맨 처음 압축을 풀면 <code>Model.xml</code> 파일 하나만 존재한다.</li>
                <li class="mt-2 list-unstyled">
                    <img src="/static/matrix/images/program_1.png" class="img-fluid rounded" alt="guide_1">
                </li>
            </ul>
        </li>
        <li class="mb-4 pb-3">
            <strong><a href="{% url 'matrix:download_file' 'Matrix 2024c.zip' %}">Matrix</a> 압축파일을 받아서 적당한 곳에 압축을 푼다.</strong>
        </li>
        <li class="mb-4 pb-3">
            <strong>Matrix.exe를 실행하고 먼저 압축을 풀었던 모델 폴더를 선택한다.</strong>
            <ul class="ps-4">
                <li>맨 처음 압축을 풀면 <code>Model.xml</code> 파일 하나만 존재한다.</li>
                <li class="mt-2 list-unstyled">
                    <img src="/static/matrix/images/program_2.png" class="rounded" alt="guide_2">
                </li>
            </ul>
        </li>
    </ol>
    <h3 class="mt-5">메인 화면</h3>
    <ul class="ps-4">
        <li><strong>테스트 설정(F8)</strong> : 테스트 설정창을 보여준다. <a href="{% url 'matrix:program_guide' 'test_flow' %}">(Test Flow 참조)</a></li>
        <li><strong>MIPI 창 열기(F10)</strong> : 현재 선택된 모델의 MIPI GUI를 보여준다.</li>
        <li><strong>Control Desk 열기(F7)</strong> : Control Desk 창을 보여준다. <a href="{% url 'matrix:program_guide' 'control_desk' %}">(Control Desk 참조)</a></li>
        <li><strong>테스트 코멘트창</strong> : 여기에 쓴 코멘트 이름으로 서브디렉토리가 생성되어 그 안에 데이터가 저장된다.</li>
        <li class="mt-2 list-unstyled">
            <img src="/static/matrix/images/program_3.png" class="img-fluid rounded" alt="guide_3">
        </li>
    </ul>
    <h3 class="mt-5">모델 변경</h3>
    <ul class="ps-4">
        <li><code>Ctrl + '0'</code>를 누르거나 타이틀 바를 우클릭하여 <code>Select Model</code>을 선택하면 다른 모델 폴더로 이동할 수 있다.</li>
        <li class="mt-2 list-unstyled">
            <img src="/static/matrix/images/program_4.png" class="img-fluid rounded" alt="guide_4">
        </li>
    </ul>
    <h3 class="mt-5">단축키</h3>
    <ul class="ps-4">
        <li><strong>F1</strong> : 프로그램 정보</li>
        <li><strong>F9</strong> : 테스트 시작</li>
        <li><strong>ESC</strong> : 테스트 즉시 멈춤</li>
        <li><strong>F8</strong> : 테스트 Flow 설정창 열기</li>
        <li><strong>F10</strong> : 모델 MIPI GUI 열기</li>
        <li><strong>F7</strong> : Control Desk 열기</li>
        <li><strong>F11</strong> : 자동스크롤 토글</li>
        <li><strong>F12</strong> : 테스트 일시정지 토글</li>
        <li><strong>Ctrl + F12</strong> : 10초간 테스트 일시정지</li>
        <li><strong>Ctrl + F5</strong> : SG에 있는 모든 Waveform을 리스팅한다. (Control Desk의 Get All Waveforms)</li>
        <li><strong>Ctrl + F6</strong> : 현재 클립보드에 복사된 Waveform을 SG에 설정한다. (Control Desk의 Set Copied Waveform)</li>
        <li><strong>Ctrl + '0'</strong> : 모델 변경</li>
        <li><strong>Ctrl + 'A'</strong> : 테스트 결과 전체선택</li>
        <li><strong>Ctrl + ' ` ' ('1'번 키 옆)</strong> : 맨 윗줄(헤더)을 제외한 테스트 결과 전체선택</li>
        <li><strong>Ctrl + 'C'</strong> : 선택된 테스트 결과 복사</li>
        <li><strong>Ctrl + '1'~'9'</strong> : 선택된 테스트 결과 중 N번째 열(세로 Column)만 복사, 특정 데이터만 복사할 때 유리</li>
    </ul>
</div>


{% endblock %}

templates/matrix/1_program_guide/test_flow.html
{% extends "matrix/matrix_base.html" %}
{% block title %}
<title>Test Flow Management</title>
{% endblock %}
{% block main_contents %}
<div class="container ms-5">
<h1 class="mb-4">Test Flow Management</h1>
    <h3 class="mt-5" >용어 설명</h3>
    <ul>
        <li >
            <strong>테스트 아이템</strong>  : 독립적으로 특정한 역할을 하거나 특정한 테스트를 진행하는 개체
        </li>
        <li >
            <strong>테스트 Flow</strong> : 테스트 아이템들을 여러개 모아서 만든 집합으로 파일 형태로 관리됨
        </li>
    </ul>
    <h3 class="mt-5" >Flow 설정 화면</h3>
    <ul>
        <li><strong>Flow 선택창</strong> : 사용하고자 하는 Flow를 Load하는 콤보박스이다.</li>
        <li><strong>Flow 관리 버튼들</strong> : Flow를 복사, 삭제, 병합할 때 사용한다.</li>
        <li><strong>테스트 장비 설정</strong> : Flow당 하나만 존재하는 특수 아이템을 보여주며 이 아이템은 현재 Flow의 장비 및 옵션을 설정하는 역할을 한다. <a href="{% url 'matrix:program_guide' 'instrument' %}">(Instrument 시트 참조)</a></li>
        <li><strong>아이템 리스트창</strong> : 현재 Flow를 구성하고 있는 아이템들을 보여준다.</li>
        <li><strong>아이템 세부설정창</strong> : 현재 선택된 아이템의 각종 옵션들을 보여주고 수정할 수 있다.</li>
        <li class="mt-2 list-unstyled">
            <img src="/static/matrix/images/flow_1.png" class="img-fluid rounded" alt="flow_1">
        </li>
    </ul>
    <h3 class="mt-5" >아이템 추가</h3>
    <ul>
        <li>Edit 모드에서 Add 버튼을 누르면 아이템 선택창이 뜬다.</li>
        <li class="mt-2 list-unstyled">
            <img src="/static/matrix/images/flow_2.png" class="img-fluid rounded" alt="flow_2">
        </li>
    </ul>
    <h3 class="mt-5" >아이템 이동 또는 자리 바꾸기</h3>
    <ul>
        <li>아이템을 Drag & Drop으로 위 아래로 이동할 수 있다..</li>
        <li class="mt-2 list-unstyled">
            <img src="/static/matrix/images/flow_3.png" class="img-fluid rounded" alt="flow_3">
        </li>
    </ul>
</div>


{% endblock %}